### ISSUE TITLE
XINPUT1_4.dll error when using Cinematic Tools (win 7 Ultimate 64Bit)

### ISSUE THREAD

**Issue by max1944** [aliasIsolation/aliasIsolation#11]
It states the XINPUT1_4.dll is missing if i select the "Load Matti Hietanen's Cinematic Tools (EXPERIMENTAL)" option within the GUI. Maybe it is incompatible with Windows 7?

**Comment by daleylife411** [comment]
Came here to say I'm getting the same error.

**Comment by z235** [comment]
Dito.

**Comment by bo3b** [comment]
I took a look at the code to see if I could fix this problem for Win7, because I know what the 1_4.dll is all about.  I thought I'd add some notes on the off chance someone takes a look at this in the future.  


It's easy enough to get it to build by changing the use of Xinput1_4.dll to the Win7 supported xinput9_1_0.dll.  I can then get past this error, but then run into another error after that, where it also required the d3dcompiler_47.dll, which comes as part of the 8.1 SDK.

The Cinematic Tools code used here has been updated to require the 8.1 SDK.  While it would be possible to remove the reliance upon the FX11 library that causes the problem, and use the better DirectXTK, it would require rewriting some of the code, and that's more effort than I'm able to provide.  I was hoping it was just a simpler build environment problem, but it's not.

So, the TAA does work fine under Windows 7, but the Cinematic Tools provided here will not work, and is unlikely to be updated.

**Comment by JayceeSantosCordova** [comment]
Whats a TAA? I just wanted to fly around the map explore/take pictures of stuff.

Does that mean we can only use this mod for window 8 or window 10 64 bit?

**Comment by bo3b** [comment]
TAA is Temporal Anti-Aliasing, which you can find with google of course.  It uses the last frame drawn to introduce a little jitter and improve the jagged lines and shimmers.

If you want the Cinematic Tools to fly around, you can only do that with OS 8.1 or above.  

TAA by itself will work on Win7.

**Comment by JayceeSantosCordova** [comment]
Thanks bo3b, btw do you know any games that the cinematic tools will work on window 7 64bit?

I really like to use this tool with re7, evil within 2, and rise of the tomb raider but i cant get it work.


thanks again!

**Comment by bo3b** [comment]
It's not a general purpose tool.  It requires a lot of deep code inspection of a given game, and figuring out internal game calls that move the camera.  

Check this link for all games supported: http://cinetools.xyz/games/

Rise of Tomb Raider is on the list, the others are not.  Might work on Win7, especially older versions of the tool.  Check the version there for Alien as well.  Might be an older version than this one.

**Comment by JayceeSantosCordova** [comment]
Hi bo3b,


The tools is not working for Rise of the Tomb Raider... I downloaded the files, check all the required depencencies, move the injector files to my ROTR game file and run the injector with admin priviledge but nothing is happening. I;m pressing the "insert" key but camera is not showing up. please help.

**Comment by JayceeSantosCordova** [comment]
Thank you so much for the info bo3b! I will try your advice. I will also try and do it on window 10 64 bit.

thanks again!

**Comment by bunnyburger0498** [comment]
I found a weird solution that works in windows 7 64 bit when you get the XINPUT1_4.dll is missing error when trying to use Matti cin tool

go to your C:\Windows\SysWOW64 folder

look for xinput1_3.dll and copy to desktop or anywhere else
(if you don't have this file, install DirectX End-User Runtimes (June 2010)  from microsoft website)
https://www.microsoft.com/en-au/download/details.aspx?id=8109

rename it to xinput1_4.dll

paste it back to C:\Windows\SysWOW64

derp it works fine now. yay!

tested with 1.0.6

you may get a window pop up saying alien isolation has crashed and is taking a dump.
just ignore the smell and don't press ok, you will notice alien isolation is still working perfectly fine.

for free cam, remember to stop time then click free cam and to read the cmd console instructions when it pops up on how to use

ps dont bother getting the original xinput1_4.dll from win8 or win10, it doesn't work because its prob dependent on other files

as for the developer, please consider compiling cinematic tool with xinput 9.1.0 or xinput 1.3 for backward compatibility if you are not going to use new functionalities of xinput 1.4, aka xbox 360

https://docs.microsoft.com/en-us/windows/desktop/xinput/xinput-versions

thanks and i hope this works for others, i fumbled this webpage from google

**Comment by bo3b** [comment]
@bunnyburger0498 Interesting workaround for the problem.  Thanks for letting us know.

Since that works out of SysWOW64, it should also work directly out of the Alien Isolation install directory.  Would be worth trying to just drop a renamed copy of xinput1_3 into the game directory.  Should work because game directory is the first search path.

**Comment by bunnyburger0498** [comment]
Thank you for that info and you are right, I have placed the renamed copy of xinput1_3 to the alien isolation game directory and it works in win7 64bit. This is probably a better solution as other softwares might malfunction if they somehow use the fake renamed xinput1_3 in SysWOW64. cheers.
