### ISSUE TITLE
Crashing on start. 

### ISSUE THREAD

**Issue by Mextrancz67** [aliasIsolation/aliasIsolation#22]
---------------------------
Fatal error
---------------------------
A fatal error was caught by Alias Isolation, and the current process will terminate.
A crash dump has been written to C:\Users\tompl\AppData\Local\Temp\aliasIsolationCrashDump.dmp.
Press Ctrl+C to copy the contents of this message to the clipboard.

aliasIsolation_hookableOverlayRender
D3D11CreateDevice
D3D11CreateDevice
D3DKMTQueryResourceInfo
D3DKMTQueryResourceInfo
DXGIGetDebugInterface1
DXGID3D10CreateLayeredDevice
CompatString
CompatString
 ?? 
 ?? 
 ?? 
CompatString
DXGIGetDebugInterface1
DXGIGetDebugInterface1
OverlayHookD3D3
D3DKMTWaitForVerticalBlankEvent
D3D11CreateDeviceAndSwapChain
aliasIsolation_hookableOverlayRender
 ?? 
 ?? 
 ?? 
BaseThreadInitThunk
RtlValidSecurityDescriptor
RtlValidSecurityDescriptor

---------------------------
OK   
---------------------------

I made sure that ALL the settings are set as they need to be.

**Comment by d0x360** [comment]
getting the same error but oddly i wasnt before when i played the game a few months ago.  Could it be an nvidia driver issue?

**Comment by Mextrancz67** [comment]
Yeah I will chek that.

**Comment by bo3b** [comment]
Most likely to be a problem introduced by Win10.  The constant updates cause a lot of problems with other modding tools.

In latest 1803, they botched how full screen works, so you might need to set the "disable full screen optimizations" in Compatibility tab.  No idea if that will solve this problem, but that lame 'optimization' broke other modding tools.

**Comment by d0x360** [comment]
I actually got it to work by using the previous version of the app.  The
one with the amd fixes.  Weird because I have an i7 5820k lol.

Anyways thank you so much for this mod.  I tried supersampling to 8k and
still saw jaggies on my 4k display.  Now the game looks flawless.

**Comment by Torrespain** [comment]
I had the same problem. To solve it I detached everything, then entered in the game and in video settings I selected windowed full screen (the game still runs in full screen) end then run the aliasIsolationInjectorGui.exe as administrator.

**Comment by d0x360** [comment]
So you ran the injector after launching? I'll try that.  I'll also do
windowed fullscreen.. if I can run the game at 4k60 with supersampling I
can afford the 5ish fps loss from not running in exlcusive fullscreen.

It's weird because an older version of the app actually does work for me
BUT it randomly crashes.  So I could be playing for 2 hours with no issues
or I might play 30 min and get a crash and lose 20 min of progress.

I actually just beat the game the other day (finally) and I want to
experiment using this mod and the mothervr mod together.  The game is so
well optimized (but with awful AA) I figure I can run this mods AA along
top supersampling in VR to get a super clean image.

Just need to wait for Thanksgiving to be over so I can have my VR space
back.  Right now there's an extra couch in the living room messing it all
up lol.

Thanks for the tips

**Comment by Torrespain** [comment]
Yes, I run the game to select windowed full screen but then I closed the game completely and run the injector. Its weird but the game runs full screen without being windowed, so perfect!
I just bought the game since it was 75% off in Steam, so far it looks great! (I've always been an alien fan)

**Comment by d0x360** [comment]
Well windowed full screen is basically full screen with the only difference
being the game doesn't get resource priority like it would in exlcusive
fullscreen.

That's why you see a slight dip in FPS but most people wouldn't notice in
this game because despite how good it looks it doesn't need super powerful
hardware

Before I got a gtx1080 i was playing on an AMD 290x and I could run it at
just shy of 4k and still hit 60fps no problem and that's with that mod that
adds planar reflections and better shadows.
