### ISSUE TITLE
any chance of a linux version for the steam deck

### ISSUE THREAD

**Issue by The-Math-God** [aliasIsolation/aliasIsolation#40]
hi as the title suggests would it be possible to make a version of this mod that can work on linux 
aka steam os on the steam deck

**Comment by HuggieBo** [comment]
Easy [workaround](https://retroresolve.com/how-to-install-the-alias-isolation-mod-on-steam-deck/) which works perfectly on deck. Set tdp to 7 if playing with 40fps or 9 with 60.

**Comment by RyanJGray** [comment]
For what it's worth, [my fork](https://github.com/RyanJGray/aliasIsolation) removes the use of the old injectors, and instead allows for the mod to be injected directly into the game when it launches, instead of it being injected into Steam and then into Alien: Isolation.
You just start the game and it injects when the game starts, adds some stuff like an in-game GUI and fixes some bugs.

This works great on Linux and Proton, I presume the same would be true for Steam Deck.

I'll merge the fork's changes into this main repository soon, so there's less of a disparity between the two versions.

**Comment by HuggieBo** [comment]
Yes your fork is the best version right now and I added it to the pc gaming wiki. I didnt know of it when I wrote my response!

**Comment by bcomnes** [comment]
> For what it's worth, [my fork](https://github.com/RyanJGray/aliasIsolation)

Any chance of upstreaming?

**Comment by RyanJGray** [comment]
> Any chance of upstreaming?

Yup, I plan to merge my fork's changes upstream very soon, once I fix the shadow jitter issue that some people have pointed out, shouldn't take long now that I have some spare time.

> Does this method work with the fork too?

It's even easier than that with the fork, to be honest.

* Download and extract the `AliasIsolation.7z` archive from the fork's releases page, to your Alien: Isolation folder (where `AI.exe` is located).
* Download the ASI injector from here:
https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/Win32-latest/d3d11-Win32.zip
* Extract that DLL to the same folder as `AI.exe`.
* Start the game, and done! :D

I've tested this on my Steam Deck with Proton Experimental and it runs pretty well on default settings.

Right now Alias Isolation will only realllllly work with the Windows version of the game without a lot of work trying to port it over to Linux natively, so using Proton will be necessary for the time being.

**Comment by Deus-nsf** [comment]
I was very hyped about this, unfortunately tested with Proton 8 and Exp on the deck, with or without the WINEDLLOVERRIDES flag set as described, it's a crash on startup.

**Comment by RyanJGray** [comment]
> I was very hyped about this, unfortunately tested with Proton 8 and Exp on the deck, with or without the WINEDLLOVERRIDES flag set as described, it's a crash on startup. I have other mods, maybe that's why, but Alias Isolation works on Windows with the same mods I use (which are basically just unpredictable and a few other tweaks)

Hmm, I'd imagine those mods aren't related to the crash on the Deck, Alias Isolation tweaks rendering, whereas those deal moreso with game data and scripting.

When it crashes, do you see a popup of some sort saying:
> A fatal error was caught by Alias Isolation, and the current process will terminate.

It might get hidden because the Deck tends to show apps in fullscreen only normally, so you might need to run the game in the Deck's desktop mode to see it.

Curious what the exact crash is, is all.

Normally, if Alias detects a crash from the mod's code, it will show that popup to aid in debugging it.

A picture of your root A:I folder (where AI.exe is) would be super useful as well, if you wouldn't mind?

Cheers!

**Comment by Deus-nsf** [comment]
[aliasIsolationCrashDump.zip](https://github.com/aliasIsolation/aliasIsolation/files/13641526/aliasIsolationCrashDump.zip)

Here you go, hope tat can be of any help, thanks for the fast answer!

**Comment by Deus-nsf** [comment]
Any luck with my info so far ? :)
