### ISSUE TITLE
Remove ASI loader mention from readme

### ISSUE THREAD

**Issue by Keith94** [aliasIsolation/aliasIsolation#53]
The release archive has ASI loader (d3d11.dll) already bundled, so no separate download needed.

EDIT: Actually, most of the README has outdated info and should be rewritten.

**Comment by RyanJGray** [comment]
Very good point, I'll fix this up now, thanks!

**Comment by RyanJGray** [comment]
No worries. Enabling motion blur and disabling chromatic aberration is still required (the README is correct in that regard) due to how the mod hijacks specific parts of the rendering in the game, I think motion blur is essential to get access to motion vector information.

I'll update the changelog to highlight that this is still the case

**Comment by Keith94** [comment]
This is helpful! Thanks. Marking as resolved
