### ISSUE TITLE
bug: v1.2.0 not loading on non-AVX CPUs

### ISSUE THREAD

**Issue by chkrefr** [aliasIsolation/aliasIsolation#54]
**Describe the bug**
I followed the setup instructions for v1.2.0 to the letter but am not seeing the `Alias Isolation` logo loading and cannot access the mod options within the game.  v1.0.6 loads without issue using the old method of launching the game with `aliasisolationinjector.exe`.

**How to reproduce**
Complete setup steps as per the readme for v1.2.0 and launch the game from Steam.
 
**Expected behaviour**
Alias Isolation to be injected, logo to appear after loading a save, mod options menu to load when pressing `DELETE`, etc.

**Setup details**
 - Game store: Steam
 - OS version: Windows 10 22H2 (fully patched as of post time)
 - GPU model: EVGA Geforce 560 Ti
 - GPU driver and version: Nvidia 391.35
 - Mod version: v1.2.0

**Additional context**
This is a fresh install on a really, really bare bones system, nothing installed that isn't needed to just get the game up and running, so very little in the way of complicating factors at play here.

**Comment by RyanJGray** [comment]
That is very strange... could you share a screenshot of your game directory (where `AI.exe` is), please?

**Comment by chkrefr** [comment]
Sure, I should have thought of that in the first place lol, hopefully this is just a dumb mistake on my part.

<img width="940" alt="Screenshot 2024-10-20 at 12 27 49 PM" src="https://github.com/user-attachments/assets/1582ad0c-e03a-4b95-9527-6accd05feb9d">

**Comment by RyanJGray** [comment]
Hmm, looks fine to me, did a file get created in `mods/aliasIsolation` called `settings.txt`?

Oh! Another thing to check would be if a file called `aliasIsolationCrashDump.dmp` exists in `%temp%` in Explorer? If it does, could you upload it here? I can have a look to see what's causing this.

**Comment by chkrefr** [comment]
No `settings.txt` file in `mods/aliasIsolation` but I did find a `aliasIsolationCrashDump.dmp` file in `%temp%`.  It was generated yesterday at the time when I first tried loading `v1.2.0` but hasn't generated a new one since despite several attempts to load this version.

I also took advantage to of an opportunity to test this on another system I had access to today and `v1.2.0` worked fine on the first try. That system is running a slower but newer GPU (Geforce 1030) which is running a much newer version of the driver (`565.90`) and I suspect that could be related.  Unfortunately `391.35` is the latest version compatible with my 560.

I could upload the `aliasIsolationCrashDump.dmp` but always hesitant to just send `dmp` files out, can you confirm that this is only a dump of the game/mod memory or is there a way I can grab what you need for you without uploading the whole thing?  I tried viewing it in `WinDbg` and it was all greek to me.

**Comment by RyanJGray** [comment]
Thanks for testing it out on another system! It's strange that it didn't generate a new dump file. 

Out of curiosity, what CPU (make and model) do you have? I'm wondering if one of my optimisations is maybe too new for your hardware?

Totally understand the security side, so that's a good question :)

The dump file only contains very limited memory from the game that is relevant to the crash itself (what code each thread of the game was executing at that point in time and a very small sample of game memory relevant to each thread) and the same for Alias itself, it doesn't dump system/OS memory or anything like that.

It is possible it could contain the user name from Windows (as your user executes the game) if you're worried about that, you could email it to me directly and I can delete the file after I've had a look into it for you? My email is: ryan@ryanjgray.com

The main info I would need is the stack trace, to see what was being executed when the crash happened (to see if Alias itself caused the crash or something else).

**Comment by chkrefr** [comment]
CPU on the system that is failing to load is an AMD `Phenom II X4 965`, it's an older one as you can see so could definitely be the culprit.

The system that is loading it without issue is running an Intel `Xeon E3-1246 v3` so that's pretty old too but a whole other class of CPU.  That system is actually a VM with the Geforce 1030 setup for PCI passthrough, funny that it works on the system with a lot more variables in play.

That tracks with the dump file, seems safe enough and there's nothing on this PC to worry about being exposed, but I just sent through email to minimize the blast radius out of an abundance of caution.  Thanks for all the help by the way, greatly appreciated.

**Comment by RyanJGray** [comment]
Ah... your Phenom lacks AVX in its instruction set (vector extensions to speed up certain math operations), that'll be the reason why it won't load, I feel. That's a cool blast from the past!

Let me build you a release that uses SSE3, which is the highest extension level the Phenom you have supports, which is also supported by the matrix math library that this mod uses.

I targeted AVX in case it would provide some performance gains and took a gamble that the majority of players would have systems supporting it (from 2011 onwards), but I'm more than happy to ship a build that uses the older extensions for situations like yours :)

No worries as well, give me a few minutes and I'll update the release on GitHub. Look for an extra archive named `AliasIsolation-v1.2.0-SSE3-Legacy.7z` and try that instead of the original archive's files.

**Comment by chkrefr** [comment]
Awesome thanks, glad to hear this could be a quick fix for you.  I'll test it out when its up and let you know how it goes.

**Comment by RyanJGray** [comment]
No problem. The new build is up for you as `AliasIsolation-v1.2.0-SSE3-Legacy.7z`, use all the files from it and hopefully it'll load up for you!

**Comment by chkrefr** [comment]
Worked like a charm, time to give myself some PTSD with upgraded graphics.  Thanks again for the quick turnaround and all the work on the mod itself.
